package io.github.miklires.mreputation;
import net.kyori.adventure.text.minimessage.MiniMessage;
import org.bukkit.Bukkit;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

final class ReputationCommand implements CommandExecutor,TabCompleter {
 private static final MiniMessage MM=MiniMessage.miniMessage(); private static final DateTimeFormatter TIME=DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm"); private final MReputation plugin;
 ReputationCommand(MReputation plugin){this.plugin=plugin;}
 public boolean onCommand(@NotNull CommandSender sender,@NotNull Command command,@NotNull String label,String[] args){String sub=args.length==0?"show":args[0].toLowerCase(Locale.ROOT);if(sub.equals("reload")){if(!allowed(sender,"mreputation.command.reload"))return true;plugin.reloadAll();send(sender,"reloaded");return true;}Target target=resolve(sender,args,sub);if(target==null){send(sender,"player-not-found");return true;}if(sub.equals("show")){if(!allowed(sender,args.length>1?"mreputation.command.show.other":"mreputation.command.show"))return true;send(sender,"show","player",target.name,"value",Integer.toString(plugin.service().get(target.id)));return true;}if(sub.equals("history")){if(!allowed(sender,"mreputation.command.history"))return true;var history=plugin.service().history(target.id);if(history.isEmpty()){send(sender,"history-empty","player",target.name);return true;}for(var e:history)send(sender,"history-line","time",TIME.format(Instant.ofEpochMilli(e.timestamp()).atZone(ZoneId.systemDefault())),"delta",signed(e.delta()),"actor",e.actor(),"reason",e.reason());return true;}if(!Set.of("add","remove","set").contains(sub)||args.length<3){send(sender,"usage");return true;}if(!allowed(sender,"mreputation.command.modify"))return true;int amount;try{amount=Integer.parseInt(args[2]);}catch(NumberFormatException e){send(sender,"invalid-number");return true;}if(amount==Integer.MIN_VALUE){send(sender,"invalid-number");return true;}String reason=args.length>3?String.join(" ",Arrays.copyOfRange(args,3,args.length)):"No reason supplied";int old=plugin.service().get(target.id);boolean changed=sub.equals("set")?plugin.service().set(target.id,target.name,amount,sender.getName(),reason):plugin.service().change(target.id,target.name,sub.equals("remove")?-Math.abs(amount):Math.abs(amount),sender.getName(),reason);int now=plugin.service().get(target.id);if(changed)send(sender,"changed","player",target.name,"old",Integer.toString(old),"new",Integer.toString(now),"delta",signed(now-old));return true;}
 private Target resolve(CommandSender sender,String[] args,String sub){String raw;if(sub.equals("show"))raw=args.length>1?args[1]:sender instanceof Player p?p.getName():null;else raw=args.length>1?args[1]:null;if(raw==null)return null;try{UUID id=UUID.fromString(raw);var off=Bukkit.getOfflinePlayer(id);return new Target(id,off.getName()==null?raw:off.getName());}catch(IllegalArgumentException ignored){}Player online=Bukkit.getPlayerExact(raw);if(online!=null)return new Target(online.getUniqueId(),online.getName());var cached=Bukkit.getOfflinePlayerIfCached(raw);return cached==null?null:new Target(cached.getUniqueId(),cached.getName()==null?raw:cached.getName());}
 private boolean allowed(CommandSender sender,String permission){if(sender.hasPermission(permission))return true;send(sender,"no-permission");return false;} private void send(CommandSender sender,String key,String...v){sender.sendMessage(MM.deserialize(plugin.messages().text(key,v)));}private static String signed(int v){return v>0?"+"+v:Integer.toString(v);}private record Target(UUID id,String name){}
 public List<String> onTabComplete(@NotNull CommandSender sender,@NotNull Command command,@NotNull String alias,String[] args){if(args.length==1)return List.of("show","add","remove","set","history","reload").stream().filter(v->v.startsWith(args[0].toLowerCase())).toList();if(args.length==2)return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(v->v.toLowerCase().startsWith(args[1].toLowerCase())).toList();return List.of();}
}
